name: student_course_enrollment_system
description: A simple system for managing student enrollments and courses.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.5

dev_dependencies:
  # Add any development dependencies here
  pedantic: ^1.11.0  # Optional, for linting and style guide

# Optional section for Flutter projects
# flutter:
#   sdk: flutter

# Add additional configuration as needed for your project
