name: student_course_enrollment_system
description: A simple student course enrollment system in Dart.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3

dev_dependencies:
  
