name: student_enrollment_system
description: enrollment system
publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  http: ^0.13.3

dev_dependencies:
  # You can add your dev dependencies here, such as test or build_runner
  # test: ^1.20.0
  # build_runner: ^2.0.0

# Additional configuration
flutter:
  uses-material-design: true # Only if you are using Flutter
